import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/shared/types/database';
import type { InvitationCode } from '../types';
import { toDomainInvitationCode } from '../transformers';
import { logger } from '@/shared';

export async function getInvitationCode(
  supabase: SupabaseClient<Database>,
  userId: string,
  communityId: string,
): Promise<InvitationCode> {
  logger.debug('🔗 API: Getting invitation code', { communityId });

  try {
    const currentUserId = userId;

    // Get the user's code for this community
    // Note: Codes are now auto-generated by database trigger when users join communities
    const { data: existingCode, error: fetchError } = await supabase
      .from('invitation_codes')
      .select('*')
      .eq('user_id', currentUserId)
      .eq('community_id', communityId)
      .eq('is_active', true)
      .maybeSingle();

    if (fetchError) {
      logger.error('🔗 API: Failed to fetch invitation code', {
        error: fetchError,
        communityId,
        userId: currentUserId,
      });
      throw fetchError;
    }

    if (!existingCode) {
      // This should not happen as codes are auto-generated when joining communities
      const error = new Error('No invitation code found for user in this community. User may not be a member.');
      logger.error('🔗 API: No invitation code found', {
        communityId,
        userId: currentUserId,
      });
      throw error;
    }

    const invitationCode = toDomainInvitationCode(existingCode);
    logger.debug('🔗 API: Found invitation code', {
      communityId,
      code: invitationCode.code,
    });
    return invitationCode;
  } catch (error) {
    logger.error('🔗 API: Error getting invitation code', {
      error,
      communityId,
    });
    throw error;
  }
}