import type { PlayerLevel } from '../types/playerLevel';

export const PLAYER_LEVELS: PlayerLevel[] = [
  {
    level: 1,
    emoji: '🦠',
    name: 'Plankton',
    pointsNeeded: 0,
    unlockedPowers: ['view_public_resources'],
  },
  {
    level: 2,
    emoji: '🐣',
    name: 'Hatchling',
    pointsNeeded: 100,
    unlockedPowers: ['create_claims'],
  },
  {
    level: 3,
    emoji: '🦐',
    name: 'Shrimp',
    pointsNeeded: 240,
    unlockedPowers: ['view_agenda'],
  },
  {
    level: 4,
    emoji: '🦀',
    name: 'Crab',
    pointsNeeded: 436,
    unlockedPowers: ['create_offer', 'create_single_event'],
  },
  {
    level: 5,
    emoji: '🦞',
    name: 'Lobster',
    pointsNeeded: 710,
    unlockedPowers: ['vote_event_time'],
  },
  {
    level: 6,
    emoji: '🪼',
    name: 'Jellyfish',
    pointsNeeded: 1095,
    unlockedPowers: ['create_request'],
  },
  {
    level: 7,
    emoji: '🐠',
    name: 'Angelfish',
    pointsNeeded: 1632,
    unlockedPowers: ['create_recurring_event'],
  },
  {
    level: 8,
    emoji: '🐡',
    name: 'Pufferfish',
    pointsNeeded: 2385,
    unlockedPowers: ['invite_friend'],
  },
  {
    level: 9,
    emoji: '🐟',
    name: 'Big Tuna',
    pointsNeeded: 3439,
    unlockedPowers: ['send_cold_call_message'],
  },
  {
    level: 10,
    emoji: '🦑',
    name: 'Squid',
    pointsNeeded: 4915,
    unlockedPowers: ['send_community_message'],
  },
  {
    level: 11,
    emoji: '🐢',
    name: 'Sea Turtle',
    pointsNeeded: 6981,
    unlockedPowers: ['view_community_map'],
  },
  {
    level: 12,
    emoji: '🐙',
    name: 'Octopus',
    pointsNeeded: 9874,
    unlockedPowers: ['join_another_community'],
  },
  {
    level: 13,
    emoji: '🦦',
    name: 'Otter',
    pointsNeeded: 13923,
  },
  {
    level: 14,
    emoji: '🦭',
    name: 'Seal',
    pointsNeeded: 19593,
  },
  {
    level: 15,
    emoji: '🐧',
    name: 'Penguin',
    pointsNeeded: 27530,
  },
  {
    level: 16,
    emoji: '🐬',
    name: 'Dolphin',
    pointsNeeded: 38642,
  },
  {
    level: 17,
    emoji: '🐋',
    name: 'Orca',
    pointsNeeded: 54199,
  },
  {
    level: 18,
    emoji: '🐳',
    name: 'Sperm Whale',
    pointsNeeded: 75978,
  },
  {
    level: 19,
    emoji: '🐋',
    name: 'Blue Whale',
    pointsNeeded: 106470,
  },
  {
    level: 20,
    emoji: '🧜',
    name: 'Mermaid',
    pointsNeeded: 149158,
  },
  {
    level: 21,
    emoji: '🌊',
    name: 'Ocean',
    pointsNeeded: 208921,
  },
  {
    level: 22,
    emoji: '🔱',
    name: 'Poseidon',
    pointsNeeded: 292589,
  },
  {
    level: 23,
    emoji: '🌎',
    name: 'Gaia',
    pointsNeeded: 409724,
  },
  {
    level: 24,
    emoji: '🌙',
    name: 'Moon',
    pointsNeeded: 573714,
  },
  {
    level: 25,
    emoji: '☀️',
    name: 'Sun',
    pointsNeeded: 803300,
  },
  {
    level: 26,
    emoji: '🪐',
    name: 'Solar System',
    pointsNeeded: 1124720,
  },
  {
    level: 27,
    emoji: '🌠',
    name: 'Shooting Star',
    pointsNeeded: 1574708,
  },
  {
    level: 28,
    emoji: '☄️',
    name: 'Comet',
    pointsNeeded: 2204691,
  },
  {
    level: 29,
    emoji: '🌟',
    name: 'North Star',
    pointsNeeded: 3086667,
  },
  {
    level: 30,
    emoji: '🌌',
    name: 'Galaxy',
    pointsNeeded: 4321434,
  },
  {
    level: 31,
    emoji: '♾️',
    name: 'Infinity',
    pointsNeeded: 6050108,
  },
];

export const MIN_SCORE = 0;
export const MAX_LEVEL = PLAYER_LEVELS.length;