import type { PlayerLevel } from '../types/playerLevel';

export const PLAYER_LEVELS: PlayerLevel[] = [
  {
    index: 0,
    emoji: '🦠',
    name: 'Plankton',
    minScore: 0,
    maxScore: 50,
  },
  {
    index: 1,
    emoji: '🐚',
    name: 'Hermit Crab',
    minScore: 50,
    maxScore: 100,
  },
  {
    index: 2,
    emoji: '🦐',
    name: 'Shrimp',
    minScore: 100,
    maxScore: 200,
  },
  {
    index: 3,
    emoji: '🦀',
    name: 'Crab',
    minScore: 200,
    maxScore: 350,
  },
  {
    index: 4,
    emoji: '🐌',
    name: 'Sea Snail',
    minScore: 350,
    maxScore: 500,
  },
  {
    index: 5,
    emoji: '🦞',
    name: 'Lobster',
    minScore: 500,
    maxScore: 750,
  },
  {
    index: 6,
    emoji: '⭐',
    name: 'Starfish',
    minScore: 750,
    maxScore: 1000,
  },
  {
    index: 7,
    emoji: '🪼',
    name: 'Jellyfish',
    minScore: 1000,
    maxScore: 1500,
  },
  {
    index: 8,
    emoji: '🐠',
    name: 'Clownfish',
    minScore: 1500,
    maxScore: 2000,
  },
  {
    index: 9,
    emoji: '🐟',
    name: 'Tuna',
    minScore: 2000,
    maxScore: 3000,
  },
  {
    index: 10,
    emoji: '🐡',
    name: 'Pufferfish',
    minScore: 3000,
    maxScore: 4000,
  },
  {
    index: 11,
    emoji: '🦑',
    name: 'Squid',
    minScore: 4000,
    maxScore: 5500,
  },
  {
    index: 12,
    emoji: '🐙',
    name: 'Octopus',
    minScore: 5500,
    maxScore: 7500,
  },
  {
    index: 13,
    emoji: '🐢',
    name: 'Sea Turtle',
    minScore: 7500,
    maxScore: 10000,
  },
  {
    index: 14,
    emoji: '🦦',
    name: 'Sea Otter',
    minScore: 10000,
    maxScore: 13000,
  },
  {
    index: 15,
    emoji: '🐧',
    name: 'Penguin',
    minScore: 13000,
    maxScore: 17000,
  },
  {
    index: 16,
    emoji: '🦭',
    name: 'Seal',
    minScore: 17000,
    maxScore: 22000,
  },
  {
    index: 17,
    emoji: '🦈',
    name: 'Shark',
    minScore: 22000,
    maxScore: 28000,
  },
  {
    index: 18,
    emoji: '🐬',
    name: 'Dolphin',
    minScore: 28000,
    maxScore: 35000,
  },
  {
    index: 19,
    emoji: '🐋',
    name: 'Whale',
    minScore: 35000,
    maxScore: undefined,
  },
];

export const MIN_SCORE = 0;
export const MAX_LEVEL_INDEX = PLAYER_LEVELS.length - 1;