import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { Button } from '../ui/button';
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from '../ui/card';
import { ImageUpload } from '../shared/ImageUpload';
import { eventBus, Resource, useBelongStore } from '@belongnetwork/core';
import { logger, logUserAction } from '@belongnetwork/core';
import { ResourceCreateFailedEvent } from '@belongnetwork/core';

interface ResourceFormProps {
  onComplete?: () => void;
  initialType?: 'offer' | 'request';
}

interface ResourceFormData {
  title: string;
  description: string;
  category: 'tools' | 'skills' | 'food' | 'supplies' | 'other';
  type: 'offer' | 'request';
  pickup_instructions: string;
  parking_info: string;
  meetup_flexibility: 'home_only' | 'public_meetup_ok' | 'delivery_possible';
  availability: string;
}

export function ResourceForm({
  onComplete,
  initialType = 'offer',
}: ResourceFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm<ResourceFormData>({
    defaultValues: {
      type: initialType,
      category: 'tools',
      meetup_flexibility: 'home_only',
    },
  });
  const [images, setImages] = useState<string[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const userLocation = useBelongStore((state) => state.auth.location);
  const currentUser = useBelongStore((state) => state.auth.user);
  const data = watch();

  // Listen for resource events
  useEffect(() => {
    const unsubscribeCreated = eventBus.on('resource.created', () => {
      logger.info('✅ ResourceForm: Resource created successfully');
      setIsSubmitting(false);
      setError(null);

      if (onComplete) {
        onComplete();
      }
    });

    const unsubscribeFailed = eventBus.on('resource.create.failed', (event) => {
      const errorEvent = event as ResourceCreateFailedEvent;
      logger.error(
        '❌ ResourceForm: Resource creation failed:',
        errorEvent.data.error
      );
      setIsSubmitting(false);
      setError(errorEvent.data.error);
    });

    return () => {
      unsubscribeCreated();
      unsubscribeFailed();
    };
  }, [onComplete]);

  const onSubmit = async (data: ResourceFormData) => {
    if (!currentUser) {
      logger.error('❌ ResourceForm: User not authenticated');
      return;
    }

    logger.debug('📦 ResourceForm: Form submitted:', data);
    logUserAction('resource_create_attempt', {
      type: data.type,
      category: data.category,
      title: data.title,
      hasImages: images.length > 0,
      imageCount: images.length,
    });

    setIsSubmitting(true);
    setError(null);

    // Emit resource creation request
    eventBus.emit('resource.create.requested', {
      ...data,
      owner_id: currentUser.id,
      image_urls: images,
      location: userLocation ?? undefined,
      is_active: true,
      times_helped: 0, // Add this required field
      created_at: new Date().toISOString(), // Add this required field
      id: '', // This will be generated by the backend
    } as Omit<Resource, 'id' | 'created_at' | 'times_helped'>);
  };

  return (
    <Card className="animate-slide-up">
      <form onSubmit={handleSubmit(onSubmit)}>
        <CardHeader>
          <CardTitle className="text-lg">
            {initialType === 'offer'
              ? 'Share a Resource'
              : 'Request a Resource'}
          </CardTitle>
        </CardHeader>

        <CardContent className="space-y-4">
          {/* Type selector */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              I want to:
            </label>
            <div className="flex gap-2">
              <label className="flex-1 cursor-pointer">
                <input
                  type="radio"
                  {...register('type')}
                  value="offer"
                  className="sr-only"
                  disabled={isSubmitting}
                />
                <div
                  className={`
                  border rounded-md p-3 text-center text-sm font-medium transition-colors
                  ${data.type === 'offer' ? 'bg-trust-50 border-trust-300 text-trust-800' : 'border-gray-200 hover:bg-gray-50'}
                `}
                >
                  Offer Something
                </div>
              </label>
              <label className="flex-1 cursor-pointer">
                <input
                  type="radio"
                  {...register('type')}
                  value="request"
                  className="sr-only"
                  disabled={isSubmitting}
                />
                <div
                  className={`
                  border rounded-md p-3 text-center text-sm font-medium transition-colors
                  ${data.type === 'request' ? 'bg-primary-50 border-primary-300 text-primary-800' : 'border-gray-200 hover:bg-gray-50'}
                `}
                >
                  Request Something
                </div>
              </label>
            </div>
          </div>

          {/* Title */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Title
            </label>
            <input
              {...register('title', { required: 'Title is required' })}
              className={`w-full border ${errors.title ? 'border-red-300' : 'border-gray-200'} rounded-md p-2 text-sm`}
              placeholder="What are you sharing or requesting?"
              disabled={isSubmitting}
            />
            {errors.title && (
              <p className="text-xs text-red-500">{errors.title.message}</p>
            )}
          </div>

          {/* Category */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Category
            </label>
            <select
              {...register('category', { required: 'Category is required' })}
              className="w-full border border-gray-200 rounded-md p-2 text-sm"
              disabled={isSubmitting}
            >
              <option value="tools">Tools</option>
              <option value="skills">Skills</option>
              <option value="food">Food</option>
              <option value="supplies">Supplies</option>
              <option value="other">Other</option>
            </select>
          </div>

          {/* Description */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Description
            </label>
            <textarea
              {...register('description', {
                required: 'Description is required',
              })}
              className={`w-full border ${errors.description ? 'border-red-300' : 'border-gray-200'} rounded-md p-2 text-sm min-h-[100px]`}
              placeholder="Provide details about what you're sharing or requesting..."
              disabled={isSubmitting}
            />
            {errors.description && (
              <p className="text-xs text-red-500">
                {errors.description.message}
              </p>
            )}
          </div>

          {/* Images */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Add photos (optional)
            </label>
            <ImageUpload onImagesUploaded={setImages} folder="resources" />
          </div>

          {/* Pickup Instructions */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Pickup Instructions
            </label>
            <textarea
              {...register('pickup_instructions')}
              className="w-full border border-gray-200 rounded-md p-2 text-sm"
              placeholder="How should people pick this up or meet you?"
              disabled={isSubmitting}
            />
          </div>

          {/* Parking Info */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Parking Information
            </label>
            <input
              {...register('parking_info')}
              className="w-full border border-gray-200 rounded-md p-2 text-sm"
              placeholder="Where can people park? (e.g., 'Driveway available', 'Street parking')"
              disabled={isSubmitting}
            />
          </div>

          {/* Meetup Flexibility */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Meetup Options
            </label>
            <select
              {...register('meetup_flexibility')}
              className="w-full border border-gray-200 rounded-md p-2 text-sm"
              disabled={isSubmitting}
            >
              <option value="home_only">Pickup at my location only</option>
              <option value="public_meetup_ok">
                Can meet at a public location
              </option>
              <option value="delivery_possible">Can deliver to you</option>
            </select>
          </div>

          {/* Availability */}
          <div className="space-y-2">
            <label className="block text-sm font-medium text-warmgray-700">
              Availability
            </label>
            <input
              {...register('availability')}
              className="w-full border border-gray-200 rounded-md p-2 text-sm"
              placeholder="When is this available? (e.g., 'Weekends only', 'Evenings after 6pm')"
              disabled={isSubmitting}
            />
          </div>

          {/* Error Display */}
          {error && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-md">
              <p className="text-sm text-red-600">{error}</p>
            </div>
          )}
        </CardContent>

        <CardFooter className="flex justify-end gap-2">
          <Button
            type="button"
            variant="outline"
            onClick={onComplete}
            disabled={isSubmitting}
          >
            Cancel
          </Button>
          <Button type="submit" disabled={isSubmitting}>
            {isSubmitting
              ? 'Submitting...'
              : data.type === 'offer'
                ? 'Share Resource'
                : 'Request Resource'}
          </Button>
        </CardFooter>
      </form>
    </Card>
  );
}
